name: Run my python

on:
  push: # do this every push

jobs:
  build:
    name: Set up environment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@0323fb13407e13b0ba941b85871d20a4db9ca552 # what kind of github action version to use
    - name: Run my python
      run: |
       python3 test.py
